providers = ["python"]

[phases.setup]
nixPkgs = [
  "python39", 
  "numpy",
  "pandas",
  "scipy",
  "gitpython",
  "matplotlib",
  "seaborn",
  "numba",
  "flask"
]

[start]
cmd = 'pip install -r dependencies.txt'
